/**
 * Content Graph — force-directed layout.
 *
 * Hand-rolled spring simulation, no d3-force dependency. Driven each
 * frame by `Pixi.Ticker`. The forces are deliberately mild so the
 * graph settles into a readable layout in a couple of seconds and
 * stays stable when the user drags a node — over-tuned forces give
 * the "vibrating gel" effect we want to avoid.
 *
 * Forces:
 *   - **Repulsion** between every pair of nodes (Coulomb-ish, falls
 *     off as 1/r²). O(n²) — fine up to ~500 nodes; Barnes-Hut can be
 *     dropped in later by replacing only this loop.
 *   - **Spring** along every edge — Hooke's law toward `SPRING_LEN`.
 *   - **Gravity** toward the world origin so disconnected components
 *     don't drift to infinity.
 *
 * Integration: explicit Euler with velocity damping. Cooling is
 * handled by `alpha`, which decays each tick and gates motion via
 * `velocity *= alpha`. When alpha falls under a threshold the sim is
 * considered settled and the ticker is parked until the user shakes
 * it (drag, filter change, focus).
 *
 * @public
 * @since 0.8.2
 */

import type { GraphEdge, GraphNode } from './types';

export interface SimOptions {
	repulsion: number;
	springK: number;
	springLen: number;
	gravity: number;
	damping: number;
}

export const DEFAULT_SIM_OPTIONS: SimOptions = {
	// Tuned to mirror Obsidian's airy graph: longer springs, weaker
	// gravity, stronger repulsion, so disconnected components drift
	// to the periphery instead of pancaking onto the connected core.
	// Repulsion is intentionally generous, on a real-world dataset
	// like Obsidian's vault you'd see most nodes isolated from the
	// connected core, and we want them spread out enough that the
	// initial fit doesn't crush every label on top of every other.
	repulsion: 26000,
	springK: 0.04,
	springLen: 200,
	gravity: 0.0035,
	damping: 0.86,
};

const ALPHA_DECAY = 0.992;
const ALPHA_MIN = 0.01;
const ALPHA_REHEAT = 1;
// Hard cap on per-step velocity so a few densely-packed nodes can't
// produce an explosive position jump in one frame. Tuned so the sim
// still feels responsive — at alpha=1 the per-frame travel cap is
// 12px, plenty for visible motion, far short of "nodes flying off".
const MAX_VELOCITY = 12;

export class ForceSim {
	public nodes: GraphNode[];
	public edges: GraphEdge[];
	public opts: SimOptions;
	/**
	 * When set, the position-update step is gated by a smoothstep
	 * falloff around this point: nodes within `dragInfluenceRadius`
	 * integrate at full per-frame alpha, nodes beyond it integrate at
	 * zero. Keeps the visible ripple of a drag local to the dragged
	 * node's neighborhood instead of cascading through every spring
	 * chain to the far edge of the graph.
	 */
	public dragOrigin: { x: number; y: number } | null = null;
	public dragInfluenceRadius = 500;
	/**
	 * Per-node group membership keys for the optional cluster-attractor
	 * force. When `null`, the cluster force is skipped entirely and the
	 * layout falls back to the existing gravity-toward-origin behaviour.
	 *
	 * Key shape is `<facet>:<id>` (e.g. `'author:42'`, `'cat:7'`,
	 * `'year:2024'`, `'cat:uncategorized'`), generated by the scene from
	 * each node's payload fields. Multi-membership posts (e.g. a post
	 * in two categories) carry multiple keys; the per-tick force
	 * weights each pull by `1 / membershipCount` so the post settles
	 * at the force balance between its centroids rather than committing
	 * to one.
	 */
	public groupAssignment: Map< number, string[] > | null = null;
	/**
	 * Optional chronological-or-otherwise-meaningful ordering for the
	 * group keys. When set, the cluster-attractor force overrides the
	 * emergent centroid X with a fixed horizontal lattice position
	 * derived from each key's index in this array, so date-based
	 * facets (year, year-month) lay out left-to-right oldest-to-
	 * newest instead of landing wherever the force balance settles.
	 *
	 * Centroid Y stays emergent — each cluster still spreads
	 * vertically based on its members, just constrained to its
	 * column. Keys absent from this array fall back to fully-
	 * emergent centroids (so an "Undated" key floats freely without
	 * needing to be jammed into the ordering).
	 */
	public groupOrder: string[] | null = null;
	public groupAttractorStrength = 0.12;
	/**
	 * Per-cluster horizontal spacing for `groupOrder`. Wide enough
	 * that repulsion between members of adjacent clusters doesn't
	 * smear them into each other on a typical zoom level.
	 */
	public groupOrderSpacing = 320;
	/**
	 * Optional vertical zig-zag for ordered clusters. When > 0 the
	 * `applyClusterAttractor` pass alternates centroid Y between
	 * `-groupOrderStaggerY` (even indices) and `+groupOrderStaggerY`
	 * (odd indices) instead of letting Y stay emergent — useful for
	 * dense ordered facets like year-month where ~60 clusters on a
	 * single horizontal line would crowd into each other. Pinning Y
	 * (not just seeding it) is necessary because the existing
	 * gravity-toward-origin force would erode an emergent Y bias
	 * over time.
	 */
	public groupOrderStaggerY = 0;
	private alpha = ALPHA_REHEAT;

	constructor(
		nodes: GraphNode[],
		edges: GraphEdge[],
		opts: SimOptions = DEFAULT_SIM_OPTIONS,
	) {
		this.nodes = nodes;
		this.edges = edges;
		this.opts = opts;
	}

	reheat( value = ALPHA_REHEAT, kick = true ): void {
		this.alpha = Math.max( this.alpha, value );
		if ( ! kick ) {
			return;
		}
		// At equilibrium every force balances to ~zero and velocities
		// have been fully damped, so just bumping alpha produces no
		// visible motion — the position update `n.x += n.vx * alpha`
		// stays at zero. Inject a small random kick proportional to
		// `value` so the cluster visibly re-settles. Pass `kick=false`
		// for the very first reheat (initial layout), where the random
		// initial positions already produce plenty of natural motion
		// from the unbalanced forces alone.
		const kickStrength = value * 3;
		for ( const n of this.nodes ) {
			if ( n.pinned ) {
				continue;
			}
			n.vx += ( Math.random() - 0.5 ) * kickStrength;
			n.vy += ( Math.random() - 0.5 ) * kickStrength;
		}
	}

	get isSettled(): boolean {
		return this.alpha < ALPHA_MIN;
	}

	/**
	 * One simulation step. `dt` defaults to 1 (one frame at the
	 * `Pixi.Ticker`'s native pace); pass a tick's `deltaTime` to
	 * compensate for frame skips.
	 */
	step( dt = 1 ): void {
		if ( this.isSettled ) {
			return;
		}

		const { repulsion, springK, springLen, gravity, damping } = this.opts;
		const nodes = this.nodes;
		const len = nodes.length;

		// Repulsion.
		for ( let i = 0; i < len; i++ ) {
			const a = nodes[ i ];
			for ( let j = i + 1; j < len; j++ ) {
				const b = nodes[ j ];
				let dx = a.x - b.x;
				let dy = a.y - b.y;
				let d2 = dx * dx + dy * dy;
				if ( d2 < 0.01 ) {
					// Co-located, give them a deterministic kick.
					dx = ( i - j ) * 0.5;
					dy = ( i + j ) * 0.5;
					d2 = dx * dx + dy * dy;
				}
				const f = repulsion / d2;
				const d = Math.sqrt( d2 );
				const fx = ( dx / d ) * f;
				const fy = ( dy / d ) * f;
				const wa = a.pinned ? 0 : 1;
				const wb = b.pinned ? 0 : 1;
				a.vx += fx * wa;
				a.vy += fy * wa;
				b.vx -= fx * wb;
				b.vy -= fy * wb;
			}
		}

		// Spring.
		for ( const e of this.edges ) {
			const dx = e.to.x - e.from.x;
			const dy = e.to.y - e.from.y;
			const d = Math.sqrt( dx * dx + dy * dy ) || 0.0001;
			const f = ( d - springLen ) * springK;
			const fx = ( dx / d ) * f;
			const fy = ( dy / d ) * f;
			if ( ! e.from.pinned ) {
				e.from.vx += fx;
				e.from.vy += fy;
			}
			if ( ! e.to.pinned ) {
				e.to.vx -= fx;
				e.to.vy -= fy;
			}
		}

		// Cluster attractor. Two-pass over the assignment map: first
		// pass averages member positions per group key to find the
		// emergent centroid; second pass pulls each non-pinned member
		// toward its centroid(s), weighted by 1/membershipCount so a
		// post in N groups settles at the force balance between them.
		this.applyClusterAttractor();

		// Gravity + integrate.
		const a = this.alpha;
		const drag = this.dragOrigin;
		const dragR = this.dragInfluenceRadius;
		const dragR2 = dragR * dragR;
		for ( const n of nodes ) {
			if ( ! n.pinned ) {
				n.vx -= n.x * gravity;
				n.vy -= n.y * gravity;
				n.vx *= damping;
				n.vy *= damping;
				// Clamp velocity so a momentary force spike (e.g.
				// initial layout where many densely-packed nodes
				// briefly push hard on each other) can't shoot a
				// node halfway across the canvas in one frame.
				if ( n.vx > MAX_VELOCITY ) {
					n.vx = MAX_VELOCITY;
				} else if ( n.vx < -MAX_VELOCITY ) {
					n.vx = -MAX_VELOCITY;
				}
				if ( n.vy > MAX_VELOCITY ) {
					n.vy = MAX_VELOCITY;
				} else if ( n.vy < -MAX_VELOCITY ) {
					n.vy = -MAX_VELOCITY;
				}
				let nodeAlpha = a;
				if ( drag ) {
					const ddx = n.x - drag.x;
					const ddy = n.y - drag.y;
					const dd2 = ddx * ddx + ddy * ddy;
					if ( dd2 >= dragR2 ) {
						nodeAlpha = 0;
					} else {
						// Smoothstep ramp: full alpha at the drag
						// origin, easing to zero at the radius edge.
						const t = 1 - Math.sqrt( dd2 ) / dragR;
						nodeAlpha *= t * t * ( 3 - 2 * t );
					}
				}
				n.x += n.vx * nodeAlpha * dt;
				n.y += n.vy * nodeAlpha * dt;
			}
		}

		this.alpha *= ALPHA_DECAY;
	}

	/**
	 * Hand each non-pinned node a pull toward its group centroid(s).
	 * Centroids are emergent — recomputed from current member positions
	 * each tick — so they drift with their cluster, rather than being
	 * pinned to a fixed lattice. Multi-membership posts (a post in two
	 * categories) receive `attractorStrength / membershipCount` of force
	 * per group, summed across their groups, so the post settles at
	 * the balance between centroids.
	 *
	 * No-op when `groupAssignment` is null.
	 */
	private applyClusterAttractor(): void {
		const assignment = this.groupAssignment;
		if ( ! assignment ) {
			return;
		}
		const k = this.groupAttractorStrength;
		if ( k <= 0 ) {
			return;
		}

		// Resolve ordered-X (and optional zig-zagged Y) positions for
		// groups carried in groupOrder (e.g. chronological lattice for
		// year / year-month). Keys not in the order array fall back
		// to emergent X / Y in pass 2.
		const orderedX = new Map< string, number >();
		const orderedY = new Map< string, number >();
		if ( this.groupOrder && this.groupOrder.length > 0 ) {
			const n = this.groupOrder.length;
			const spacing = this.groupOrderSpacing;
			const stagger = this.groupOrderStaggerY;
			for ( let i = 0; i < n; i++ ) {
				const key = this.groupOrder[ i ];
				orderedX.set( key, ( i - ( n - 1 ) / 2 ) * spacing );
				if ( stagger > 0 ) {
					// Alternate above / below the horizontal axis so
					// adjacent clusters don't crowd each other on
					// dense facets like year-month.
					orderedY.set( key, i % 2 === 0 ? -stagger : stagger );
				}
			}
		}

		// Pass 1: per-group running sum of member positions.
		const centroids = new Map< string, { sx: number; sy: number; count: number } >();
		for ( const n of this.nodes ) {
			const keys = assignment.get( n.id );
			if ( ! keys || keys.length === 0 ) {
				continue;
			}
			for ( const key of keys ) {
				const c = centroids.get( key );
				if ( c ) {
					c.sx += n.x;
					c.sy += n.y;
					c.count++;
				} else {
					centroids.set( key, { sx: n.x, sy: n.y, count: 1 } );
				}
			}
		}

		// Pass 2: apply per-membership pulls. Centroid Y is always the
		// running average; centroid X is the ordered lattice position
		// when the key carries one, otherwise the running average.
		for ( const n of this.nodes ) {
			if ( n.pinned ) {
				continue;
			}
			const keys = assignment.get( n.id );
			if ( ! keys || keys.length === 0 ) {
				continue;
			}
			const perKey = k / keys.length;
			for ( const key of keys ) {
				const c = centroids.get( key );
				if ( ! c || c.count === 0 ) {
					continue;
				}
				const cx = orderedX.has( key )
					? ( orderedX.get( key ) as number )
					: c.sx / c.count;
				const cy = orderedY.has( key )
					? ( orderedY.get( key ) as number )
					: c.sy / c.count;
				n.vx += ( cx - n.x ) * perKey;
				n.vy += ( cy - n.y ) * perKey;
			}
		}
	}

	/**
	 * Public hand-off used by the scene when the toolbar's group-by
	 * selector changes. Pass `null` for the map to disable clustering
	 * and fall back to the existing gravity-toward-origin layout.
	 * The optional `order` argument pins listed group keys to a
	 * left-to-right horizontal lattice (chronological for date
	 * facets); keys not in `order` keep emergent centroids.
	 *
	 * The sim is reheated so the new force visibly settles instead
	 * of waiting for the next external nudge.
	 */
	setGroupAssignment(
		map: Map< number, string[] > | null,
		order: string[] | null = null,
	): void {
		this.groupAssignment = map;
		this.groupOrder = map ? order : null;
		this.reheat( 0.3, false );
	}
}
